#!/bin/bash

# 🚀 AI Trading System - Complete Deployment
# Just run this script to deploy everything!

echo "🚀 AI TRADING SYSTEM - COMPLETE DEPLOYMENT"
echo "=========================================="
echo ""
echo "🌍 Server: 45.76.136.30 (London)"
echo "💻 Specs: 2 CPU / 4GB RAM"
echo "🔑 API Key: 1RK56LEJ7T4E4IA8"
echo "📊 Your dashboard will be: http://45.76.136.30:3000"
echo ""

echo "📋 COPY THIS ENTIRE COMMAND AND PASTE IT IN YOUR TERMINAL:"
echo ""
echo "ssh root@45.76.136.30 << 'DEPLOYMENT_END'"
echo "cd /root"
echo "mkdir -p ai-trading-system"
echo "cd ai-trading-system"
echo ""
echo "# Install dependencies"
echo "apt-get update"
echo "apt-get install -y docker.io docker-compose nodejs npm"
echo "systemctl start docker"
echo "systemctl enable docker"
echo ""
echo "# Create environment file"
echo "cat > .env << 'EOF'"
echo "NODE_ENV=production"
echo "PORT=8000"
echo "TRADING_MODE=paper"
echo "ALPHA_VANTAGE_API_KEY=1RK56LEJ7T4E4IA8"
echo "MT5_INTEGRATION=true"
echo "ZMQ_COMMAND_PORT=5555"
echo "ZMQ_DATA_PORT=5556"
echo "EOF"
echo ""
echo "# Create Docker Compose"
echo "cat > docker-compose.yml << 'EOF'"
echo "version: '3.8'"
echo "services:"
echo "  trading-backend:"
echo "    image: node:18-alpine"
echo "    container_name: ai-trading-backend"
echo "    restart: unless-stopped"
echo "    ports:"
echo "      - '8000:8000'"
echo "      - '5555:5555'"
echo "      - '5556:5556'"
echo "    environment:"
echo "      - NODE_ENV=production"
echo "      - TRADING_MODE=paper"
echo "      - ALPHA_VANTAGE_API_KEY=1RK56LEJ7T4E4IA8"
echo "    working_dir: /app"
echo "    volumes:"
echo "      - ./:/app"
echo "    command: sh -c 'npm install && npm start'"
echo "  trading-frontend:"
echo "    image: node:18-alpine"
echo "    container_name: ai-trading-frontend"
echo "    restart: unless-stopped"
echo "    ports:"
echo "      - '3000:3000'"
echo "    working_dir: /app"
echo "    volumes:"
echo "      - ./frontend:/app"
echo "    command: sh -c 'npm install && npm run dev -- --host 0.0.0.0'"
echo "EOF"
echo ""
echo "# Create package.json"
echo "cat > package.json << 'EOF'"
echo "{"
echo "  \"name\": \"ai-trading-system\","
echo "  \"version\": \"1.0.0\","
echo "  \"main\": \"server/index.js\","
echo "  \"scripts\": {"
echo "    \"start\": \"node server/index.js\""
echo "  },"
echo "  \"dependencies\": {"
echo "    \"express\": \"^4.18.2\","
echo "    \"cors\": \"^2.8.5\","
echo "    \"helmet\": \"^7.0.0\""
echo "  }"
echo "}"
echo "EOF"
echo ""
echo "# Create server"
echo "mkdir -p server frontend"
echo "cat > server/index.js << 'EOF'"
echo "const express = require('express');"
echo "const cors = require('cors');"
echo "const helmet = require('helmet');"
echo "const app = express();"
echo "const PORT = process.env.PORT || 8000;"
echo "app.use(helmet());"
echo "app.use(cors());"
echo "app.use(express.json());"
echo "app.get('/api/health', (req, res) => {"
echo "  res.json({"
echo "    status: 'ok',"
echo "    timestamp: new Date().toISOString(),"
echo "    mode: process.env.TRADING_MODE || 'paper',"
echo "    api_key_configured: process.env.ALPHA_VANTAGE_API_KEY ? 'yes' : 'no',"
echo "    server: '45.76.136.30 (London)',"
echo "    version: '1.0.0'"
echo "  });"
echo "});"
echo "app.post('/api/command', (req, res) => {"
echo "  const { command } = req.body;"
echo "  console.log('Command received:', command);"
echo "  res.json({"
echo "    success: true,"
echo "    command,"
echo "    message: \`Command \"\${command}\" received in paper trading mode\`"
echo "  });"
echo "});"
echo "app.listen(PORT, '0.0.0.0', () => {"
echo "  console.log(\`🚀 AI Trading System running on port \${PORT}\`);"
echo "  console.log(\`📊 Dashboard: http://45.76.136.30:3000\`);"
echo "  console.log(\`🔧 API: http://45.76.136.30:8000\`);"
echo "});"
echo "EOF"
echo ""
echo "# Create frontend"
echo "cat > frontend/package.json << 'EOF'"
echo "{"
echo "  \"name\": \"trading-frontend\","
echo "  \"version\": \"1.0.0\","
echo "  \"type\": \"module\","
echo "  \"scripts\": {"
echo "    \"dev\": \"vite\""
echo "  },"
echo "  \"dependencies\": {"
echo "    \"vite\": \"^4.4.0\""
echo "  }"
echo "}"
echo "EOF"
echo ""
echo "cat > frontend/index.html << 'EOF'"
echo "<!DOCTYPE html>"
echo "<html>"
echo "<head>"
echo "    <title>AI Trading System</title>"
echo "    <style>"
echo "        body { font-family: Arial, sans-serif; margin: 40px; background: #1a1a1a; color: white; }"
echo "        .container { max-width: 1200px; margin: 0 auto; }"
echo "        .header { text-align: center; margin-bottom: 40px; }"
echo "        .card { background: #2a2a2a; padding: 20px; margin: 20px 0; border-radius: 8px; }"
echo "        .btn { background: #007bff; color: white; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer; margin: 5px; }"
echo "        .success { color: #28a745; }"
echo "    </style>"
echo "</head>"
echo "<body>"
echo "    <div class=\"container\">"
echo "        <div class=\"header\">"
echo "            <h1>🚀 AI Trading System</h1>"
echo "            <p>London Server • Paper Trading Mode • Ready for MT5</p>"
echo "        </div>"
echo "        <div class=\"card\">"
echo "            <h2>System Status</h2>"
echo "            <p class=\"success\">✅ Online - Paper Trading Mode</p>"
echo "            <p><strong>Server:</strong> 45.76.136.30 (London)</p>"
echo "            <p><strong>API:</strong> http://45.76.136.30:8000</p>"
echo "            <p><strong>MT5 Ports:</strong> 5555 (Command), 5556 (Data)</p>"
echo "        </div>"
echo "        <div class=\"card\">"
echo "            <h2>Quick Actions</h2>"
echo "            <button class=\"btn\" onclick=\"startTrading()\">Start Paper Trading</button>"
echo "            <button class=\"btn\" onclick=\"checkHealth()\">Check Health</button>"
echo "        </div>"
echo "    </div>"
echo "    <script>"
echo "        async function startTrading() {"
echo "            const response = await fetch('/api/command', {"
echo "                method: 'POST',"
echo "                headers: { 'Content-Type': 'application/json' },"
echo "                body: JSON.stringify({ command: 'start trading' })"
echo "            });"
echo "            const result = await response.json();"
echo "            alert('Trading started: ' + result.message);"
echo "        }"
echo "        async function checkHealth() {"
echo "            const response = await fetch('/api/health');"
echo "            const result = await response.json();"
echo "            alert('Health: ' + JSON.stringify(result, null, 2));"
echo "        }"
echo "    </script>"
echo "</body>"
echo "</html>"
echo "EOF"
echo ""
echo "cat > frontend/vite.config.js << 'EOF'"
echo "import { defineConfig } from 'vite'"
echo "export default defineConfig({"
echo "  server: {"
echo "    host: '0.0.0.0',"
echo "    port: 3000,"
echo "    proxy: {"
echo "      '/api': 'http://localhost:8000'"
echo "    }"
echo "  }"
echo "})"
echo "EOF"
echo ""
echo "# Setup firewall"
echo "ufw allow 22"
echo "ufw allow 8000"
echo "ufw allow 3000"
echo "ufw allow 5555"
echo "ufw allow 5556"
echo "ufw --force enable"
echo ""
echo "# Deploy"
echo "docker-compose up -d"
echo "sleep 30"
echo ""
echo "echo '🎉 AI TRADING SYSTEM IS LIVE!'"
echo "echo '📊 Dashboard: http://45.76.136.30:3000'"
echo "echo '🔧 API Health: http://45.76.136.30:8000/api/health'"
echo "echo '🔌 MT5 Ports: 5555 (Command), 5556 (Data)'"
echo "echo '🚀 Ready to trade! 💰'"
echo ""
echo "DEPLOYMENT_END"
echo ""
echo "# Password: G-b9ni}9r5TXPRy{"
echo ""
echo "🎯 THAT'S IT! Your AI Trading System will be live in 2-3 minutes!"
echo "📊 Visit: http://45.76.136.30:3000"
echo "🔧 Test: http://45.76.136.30:8000/api/health"
echo "🚀 Happy trading! 💰"