services:
  - type: web
    name: algo-trading-system
    env: node
    buildCommand: npm ci --only=production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
    healthCheckPath: /api/health
    autoDeploy: true
    plan: starter

databases:
  - name: redis
    databaseName: redis
    plan: starter 