[build]
# Explicitly use Dockerfile for build
builder = "dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
replicas = 1

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"
ALLOWED_ORIGINS = "https://your-frontend-domain.com,http://localhost:5173"
NODE_OPTIONS = "--max-old-space-size=512" 